[tox]
envlist = begin,py3{10,11,12,13,14},end
          py3{10,11,12,13,14}-functional
          installer,ruff,ruff-check,mypy
minversion = 2.0
skipsdist = false
skip_missing_interpreters = true

[testenv]
runner = uv-venv-lock-runner
extras =
  test
setenv =
  PACKAGE_NAME=exordos
  TEST_PATH={env:PACKAGE_NAME}/tests/unit
  functional: TEST_PATH={env:PACKAGE_NAME}/tests/functional
commands =
  coverage run -p -m pytest {posargs} --timer-top-n=10 {env:TEST_PATH}
allowlist_externals =
  markdownlint-cli2
  find
  git

[testenv:begin]
runner = uv-venv-lock-runner
envdir = {toxworkdir}/cover
commands =
  coverage erase

[testenv:end]
runner = uv-venv-lock-runner
envdir = {toxworkdir}/cover
commands =
  coverage combine
  coverage html -d cover
  coverage xml -o cover/coverage.xml
  coverage report --skip-covered

[testenv:ruff-check]
extras =
  ruff
runner = uv-venv-lock-runner
commands = ruff check .

[testenv:ruff]
extras =
  ruff
runner = uv-venv-lock-runner
commands =
  ruff check . --fix
  ruff check --select I --fix
  ruff format

[testenv:mypy]
extras =
  mypy
runner = uv-venv-lock-runner
commands = mypy -p exordos

[testenv:docs]
extras =
  docs
runner = uv-venv-lock-runner
commands = mkdocs serve --dev-addr 0.0.0.0:8181 --livereload

[testenv:docs-deploy]
extras =
  docs
runner = uv-venv-lock-runner
commands = mkdocs gh-deploy --force

[testenv:develop]
runner = uv-venv-lock-runner
extras =
  test
usedevelop=true

[testenv:bin]
basepython = python3.14
extras =
  bin
runner = uv-venv-lock-runner
commands = pyinstaller {posargs:--onefile} --name exordos --recursive-copy-metadata exordos --add-data="exordos/packer/*:exordos/packer" --hidden-import=exordos.packer --add-data="exordos/repo/*:exordos/repo" --hidden-import=exordos.repo --add-data="exordos/templates/*:exordos/templates" --add-data="exordos/autocomplete/*:exordos/autocomplete" --add-data="exordos/spec/*:exordos/spec" --collect-data openapi_schema_validator ./exordos/cmd/cli.py

[testenv:installer]
extras =
  shellcheck
runner = uv-venv-lock-runner
allowlist_externals =
  sh
commands =
  shellcheck -s sh -e SC1091,SC2016,SC2034,SC2086,SC2251,SC3043 etc/install.sh etc/package-macos.sh etc/tests/test-install-macos.sh
  sh etc/tests/test-install-macos.sh

[testenv:cli_docs]
runner = uv-venv-lock-runner
setenv =
  PACKAGE_NAME=exordos
  TEST_PATH={env:PACKAGE_NAME}/tests/manual/test_cli.py
commands =
  find docs/cli -name "*md" -delete
  pytest {posargs} {env:TEST_PATH}
  git add docs/cli
