name: build binary

on:
  workflow_dispatch:

jobs:
  build_binaries:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact-suffix: linux
            python-version: "3.14"
          - os: macos-latest
            artifact-suffix: macos-arm
            python-version: "3.14"
          - os: windows-latest
            artifact-suffix: windows
            python-version: "3.14"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 30
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install deps (Linux)
        if: runner.os == 'Linux'
        run: sudo apt update && sudo apt install --yes ca-certificates
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Install tox-uv
        run: uv tool install tox --with tox-uv
      - name: Build executable
        run: tox -e bin
      - name: Rename executable
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            mv dist/exordos.exe dist/exordos-${{ matrix.artifact-suffix }}.exe
          else
            mv dist/exordos dist/exordos-${{ matrix.artifact-suffix }}
          fi
        shell: bash
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: exordos-${{ matrix.artifact-suffix }}
          path: dist/*