name: Publish Python 🐍 distribution 📦 and binaries

on:
  push:
    tags:
      - '*'

env:
  PROJECT_NAME: exordos
  DEVTOOLS_PATH: https://repo.exordos.com/exordos/
  REPO_ENDPOINT_PUT: http://10.20.0.1:8082

jobs:
  build_python:
    name: Build distribution 📦
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
      with:
        persist-credentials: false
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.14"
    - name: Install pypa/build
      run: >-
        python3 -m
        pip install
        build
        --user
    - name: Build a binary wheel and a source tarball
      run: python3 -m build
    - name: Store the distribution packages
      uses: actions/upload-artifact@v7
      with:
        name: python-package-distributions
        path: dist/

  publish-to-pypi:
    name: Publish Python 🐍 distribution 📦 to PyPI
    needs:
    - build_python
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/exordos
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v8
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1

  build_binaries:
    strategy:
      matrix:
        include:
          - os: ubuntu-26.04
            artifact-suffix: linux-ubuntu-resolute
            python-version: "3.14"
          - os: ubuntu-latest
            artifact-suffix: linux
            python-version: "3.14"
          - os: macos-latest
            artifact-suffix: macos-arm
            python-version: "3.14"
          - os: windows-latest
            artifact-suffix: windows
            python-version: "3.14"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 30
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install deps (Linux)
        if: runner.os == 'Linux'
        run: sudo apt update && sudo apt install --yes ca-certificates
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Install tox-uv
        run: uv tool install tox --with tox-uv
      - name: Build executable
        run: tox -e bin
      - name: Rename executable
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            mv dist/exordos.exe dist/exordos-${{ matrix.artifact-suffix }}.exe
          else
            mv dist/exordos dist/exordos-${{ matrix.artifact-suffix }}
          fi
        shell: bash
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: exordos-${{ matrix.artifact-suffix }}
          path: dist/*

  github-release:
    name: Create GitHub Release with artifacts
    needs:
    - publish-to-pypi
    - build_binaries
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
    - name: Download Python distributions
      uses: actions/download-artifact@v8
      with:
        name: python-package-distributions
        path: dist/
    - name: Download Linux binary
      uses: actions/download-artifact@v8
      with:
        name: exordos-linux
        path: dist/
    - name: Download Linux ubuntu-resolute binary
      uses: actions/download-artifact@v8
      with:
        name: exordos-linux-ubuntu-resolute
        path: dist/
    - name: Download macOS arm binary
      uses: actions/download-artifact@v8
      with:
        name: exordos-macos-arm
        path: dist/
    - name: Download Windows binary
      uses: actions/download-artifact@v8
      with:
        name: exordos-windows
        path: dist/
    - name: Create GitHub Release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: >-
        gh release create
        "$GITHUB_REF_NAME"
        --repo "$GITHUB_REPOSITORY"
        --notes ""
    - name: Upload release artifacts
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: >-
        gh release upload
        "$GITHUB_REF_NAME" dist/**
        --repo "$GITHUB_REPOSITORY"

  exordos-release:
    name: Create exordos Release with artifacts
    needs:
    - build_binaries
    runs-on: self-hosted
    steps:
    - name: Download Linux binary
      uses: actions/download-artifact@v8
      with:
        name: exordos-linux
        path: dist/
    - name: Download Linux ubuntu-resolute binary
      uses: actions/download-artifact@v8
      with:
        name: exordos-linux-ubuntu-resolute
        path: dist/
    - name: Download macOS arm binary
      uses: actions/download-artifact@v8
      with:
        name: exordos-macos-arm
        path: dist/
    - name: Download Windows binary
      uses: actions/download-artifact@v8
      with:
        name: exordos-windows
        path: dist/
    - name: Push artifacts to repository
      run: |
        set -eux
        chmod +x ./dist/exordos-linux
        VERSION=$(./dist/exordos-linux --silent version)

        # Upload VERSION release
        curl -X PUT --upload-file ./dist/exordos-linux \
          $REPO_ENDPOINT_PUT/${PROJECT_NAME}/${VERSION}/exordos-linux
        curl -X PUT --upload-file ./dist/exordos-linux-ubuntu-resolute \
          $REPO_ENDPOINT_PUT/${PROJECT_NAME}/${VERSION}/exordos-linux-ubuntu-resolute
        curl -X PUT --upload-file ./dist/exordos-macos-arm \
          $REPO_ENDPOINT_PUT/${PROJECT_NAME}/${VERSION}/exordos-macos-arm
        curl -X PUT --upload-file ./dist/exordos-windows.exe \
          $REPO_ENDPOINT_PUT/${PROJECT_NAME}/${VERSION}/exordos-windows.exe

        # Upload latest release
        curl -X PUT --upload-file ./dist/exordos-linux \
          $REPO_ENDPOINT_PUT/${PROJECT_NAME}/latest/exordos-linux
        curl -X PUT --upload-file ./dist/exordos-linux \
          $REPO_ENDPOINT_PUT/${PROJECT_NAME}/latest/exordos-linux-ubuntu-resolute
        curl -X PUT --upload-file ./dist/exordos-macos-arm \
          $REPO_ENDPOINT_PUT/${PROJECT_NAME}/latest/exordos-macos-arm
        curl -X PUT --upload-file ./dist/exordos-windows.exe \
          $REPO_ENDPOINT_PUT/${PROJECT_NAME}/latest/exordos-windows.exe
