name: Upload and update on self-hosted

on: workflow_dispatch

env:
  REPO_ENDPOINT_PUT: http://10.20.0.1:8082

jobs:
  upload-install-sh:
    name: Upload install.sh
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v7
      with:
        persist-credentials: false
    - name: Push artifacts to repository
      run: curl -X PUT --upload-file ./etc/install.sh $REPO_ENDPOINT_PUT/install.sh

  update-exordos-cli:
    name: update exordos cli
    needs: upload-install-sh
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ github-packer-runner-1, github-packer-runner-2, github-packer-runner-3, genesis-lab0 ]
    steps:
    - name: update exordos cli
      run: |
        set -eux

        curl -fsSL https://repo.exordos.com/install.sh | sudo sh
        
        which exordos
        exordos version
 
